# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_habitacion', models.IntegerField()),
                ('personas', models.IntegerField()),
                ('estado', models.CharField(choices=[('1', 'ocupada'), ('0', 'desocupada')], max_length=1)),
                ('clasificacion', models.BooleanField()),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Precio', models.IntegerField()),
                ('tipo_de_pago', models.BooleanField(choices=[('E', 'efectivo'), ('T', 'tarjeta')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personas_por_habitacion', models.IntegerField()),
                ('entrada', models.DateField()),
                ('salida', models.DateField()),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Boletin.Habitaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('DNI', models.IntegerField()),
                ('administrador', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Boletin.Usuario'),
        ),
        migrations.AddField(
            model_name='pago',
            name='referencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Boletin.Reserva'),
        ),
    ]
