# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boletin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='tipodepago',
        ),
        migrations.AddField(
            model_name='pago',
            name='tipo_pago',
            field=models.CharField(choices=[('E', 'efectivo'), ('T', 'tarjeta')], default='E', max_length=1),
        ),
    ]
