# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boletin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitaciones',
            name='clasificacion',
            field=models.CharField(choices=[('1', 'simple'), ('2', 'matrimonial'), ('3', 'doble'), ('4', 'triple')], max_length=1),
        ),
    ]
