# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Boletin', '0002_auto_20161104_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitaciones',
            name='disponible',
        ),
    ]
