# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boletin', '0004_auto_20161104_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitaciones',
            name='num_habitacion',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.CharField(max_length=8),
        ),
    ]
